### PR TITLE
Update path handling based on smoke test

### PR DESCRIPTION
**Pull request by rsheeter**
Try to avoid setting off debug_assert's in BezPath :)

I mistakenly assumed a BezPath with a move would not be empty but it (correctly) is. Correct our interrogation of the BezPath.

Smoke test UFOs love to open with a curve and close with dangling offcurve; support that. 

https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#point-types suggests more variants than I've supported thus far should work. qcurve is also unimplemented. Baby steps.

### CODE REVIEW

**Comment by anthrotype** [comment]
> UFOs love to open with a curve and close with dangling offcurve

I'd say that's the 'canonical' way whereby UFO GLIF points are serialized, always starting with an oncurve

**Comment by anthrotype** [comment]
why is this a separate PR and not folded into #104 instead? seems realtively small to be a commit, rather than standalone PR

**Comment by rsheeter** [comment]
> I'd say that's the 'canonical' way whereby UFO GLIF points are serialized, always starting with an oncurve

Good to know. The spec offers no such guidance but reality agrees.

> why is this a separate PR

Purely because I sent the former for review first. I'll fold them by merging this into that (which is how it's setup anyway).

**Comment by anthrotype** [comment]
> Purely because I sent the former for review first

I think you can just add commit to a PR that's already been reviewed, and notify the reviewers that you added something you want to be reviewed. I find confusing/distracting when when there are several PRs piling up on top of one another each one touching the same code; the reviewer has to figure out in which order they are related to one another and to the main branch, then may spend time reviewing some part of the code that will be rendered obsolete by some other follow-up PR that's waiting in the queue. I think it's just better to consolidate all PRs that touch upon the same files into one, but that's just my opinion.

**Comment by rsheeter** [comment]
I agree re merging when it's related or the it's the same bit of code, as was the case here. If it wasn't so related then maybe not even if it was the same files?

The order is apparent from the branches so I'd have hoped that wasn't too time consuming.

**Comment by anthrotype** [comment]
sounds good to me

**Pull request merged**
