### PR TITLE
Use font_types NameId

### LINKED ISSUE #196: Use font_types::NameId
It SHOUTS_AT_YOU but having two definitions is worse.

### PR DESCRIPTION
**Pull request by rsheeter**
Fixes #196

For some reason serde kept puking when I try to handle name id as a u16 so I made it a string. Ex `'Unable to deserialize "/tmp/.tmpRPdlUn/static_metadata.preliminary.yml" names.name_id: invalid type: integer `2`, expected A valid NameId at line 3 column 14'`

### CODE REVIEW

**Review by dfrg — APPROVED** [review]
Looks good. While reading, I realized that POSTSCRIPT should probably be POST_SCRIPT for consistency. I’ll fix both projects in another set of PRs.

**Comment by khaledhosny** [comment]
Isn't PostScript is one word?

**Comment by dfrg** [comment]
To me, the pascal casing as you’ve written it suggests it should include an underscore when converted to (screaming) snake case. We use `post_script` elsewhere in field/variable names.

**Comment by rsheeter** [comment]
This PR is definiltely CHAD_YELLING_AT_ME

**Comment by khaledhosny** [comment]
HarfBuzz uses `HB_OT_NAME_ID_POSTSCRIPT_NAME` and that feels more natural to me, `post_script` feels odd as well as that reads like the opposite of `pre_script`.

**Comment by dfrg** [comment]
Fair enough. I’m happy to go the other way as long as we’re consistent.

**Pull request merged**
